version: '3.8'
services:
  workspace:
    build: .
    volumes:
      - .:/workspace/repo
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    command: 
      - bash 
      - -c
      - |
        python3 program1.py
        eog plot.png
        sleep infinity 
  

